---
# When a pull request is made to the main branch, deploy an
# instance of the API

name: Deploy API
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    
    - name: Create dokku app if dosent already exist using dokku apps:create
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
      run: |
        set -x
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.DOKKU_HOST }}>> ~/.ssh/known_hosts
        eval `ssh-agent -s`
        ssh-add - <<< "$SSH_PRIVATE_KEY"
        ssh dokku@$DOKKU_HOST -C "dokku apps:create search-transactions" | true

    - name: Deploy
      run: |
        set -x
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.DOKKU_HOST }}>> ~/.ssh/known_hosts
        eval `ssh-agent -s`
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY}}"
        ssh dokku@${{ secrets.DOKKU_HOST }} -C "dokku git:sync --build search-transactions https://github.com/KarmaComputing/search-transactions.git main"
        ssh dokku@${{ secrets.DOKKU_HOST }} -C "dokku letsencrypt:enable search-transactions"
        ssh dokku@${{ secrets.DOKKU_HOST }} -C "dokku letsencrypt:cron-job --add"

